name: Run Assignment1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.7

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the unit tests
    - name: Run pytest
      run: |
        pytest --cov=array_to_array

    # Step 5: Include test CSV files
    - name: Create test CSV files
      run: |
        echo "Latitude,Longitude\n33.9425,-118.4081\n37.6213,-122.3790" > us-airports.csv
        echo "Latitude,Longitude\n34.0522,-118.2437\n40.7128,-74.0060" > us-cities-top-1k.csv

    # Step 6: Run the Python script with the test CSV files
    - name: Run the script
      run: |
        python array_to_array.py --csv1 us-airports.csv --csv2 us-cities-top-1k.csv
